name: Trigger auto deployment for test1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test1-AutoDeployTrigger-b78e3f4e-e10d-403d-85c5-6c8d370b43f9.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acrfromdevopscosmosdbconf23.azurecr.io
          username: ${{ secrets.TEST1_REGISTRY_USERNAME }}
          password: ${{ secrets.TEST1_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrfromdevopscosmosdbconf23.azurecr.io/containerappsalbumapijavascript:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TEST1_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n test1 -g containerapps --server acrfromdevopscosmosdbconf23.azurecr.io --username  ${{ secrets.TEST1_REGISTRY_USERNAME }} --password ${{ secrets.TEST1_REGISTRY_PASSWORD }}
            az containerapp update -n test1 -g containerapps --image acrfromdevopscosmosdbconf23.azurecr.io/containerappsalbumapijavascript:${{ github.sha }}
